#ifndef VARS1_H
#define VARS1_H

#include "vars.c"

extern char *CESAR_ENCRYPT_OPTION;
extern char *CESAR_DENCRYPT_OPTION;
extern char *MATH_ENCRYPT_OPTION;
extern char *MATH_DENCRYPT_OPTION;

extern char *VGN_ENCRYPT_OPTION;
extern char *VGN_DENCRYPT_OPTION;

extern char *VGM_ENCRYPT_OPTION;
extern char *VGM_DENCRYPT_OPTION;



extern int ASCII_CHARACTERS_LENGTH;

extern int ASCII_INTERVAL_START_FOR_LOWERCASE_LETTERS;
extern int ASCII_INTERVAL_END_FOR_LOWERCASE_LETTERS;

extern int ASCII_INTERVAL_START_FOR_UPPERCASE_LETTERS;
extern int ASCII_INTERVAL_END_FOR_UPPERCASE_LETTERS;

extern char ALPHABET[];
extern char FULL_ALPHABET[];

#endif
